---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  type: ClusterIP
  ports:
    - name: search-port
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: search-service
subsets:
  - addresses:
      - ip: 192.168.174.133
      - ip: 192.168.153.230
      #- hostname: vpc-elastic-arch-crds2fuwl3aii5dxya5w5qchca.us-west-2.es.amazonaws.com
    ports:
      - port: 443
---
kind: Service
apiVersion: v1
metadata:
 name: search-service1
spec:
 type: ExternalName
 externalName: vpc-elastic-arch-crds2fuwl3aii5dxya5w5qchca.us-west-2.es.amazonaws.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: search-main
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #kubernetes.io/tls-acme: "false"
spec:
   tls:
   - secretName: tls-cert
     hosts:
     - es.internal.bhn.technology
   rules:
    - host: es.internal.bhn.technology
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: search-service1
              port:
                number: 443
